service: ${opt:service}-service

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'production'}
  region: ${file(./services/${opt:service}.yml):region}
  iamRoleStatements: ${file(./services/${opt:service}.yml):iam}
  environment: ${file(./services/${opt:service}.yml):env}

  deploymentBucket: remotepixel-${self:provider.region}

package:
  artifact: package.zip

functions: ${file(./services/${opt:service}.yml):functions}
