service: ${opt:sat}-service

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'production'}
  region: ${file(./satellites/${opt:sat}.yml):region}
  iamRoleStatements: ${file(./satellites/${opt:sat}.yml):iam}
  environment: ${file(./satellites/${opt:sat}.yml):env}

  deploymentBucket: remotepixel-${self:provider.region}

package:
  artifact: package.zip

functions: ${file(./satellites/${opt:sat}.yml):functions}
